# Generated by Django 5.2.15 on 2026-07-02 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(max_length=10, unique=True, verbose_name="記号"),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=80, verbose_name="意味"),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(default=5, verbose_name="優先度"),
                ),
                (
                    "assignable",
                    models.BooleanField(default=True, verbose_name="配置可"),
                ),
                (
                    "instructor",
                    models.BooleanField(default=False, verbose_name="指導可能"),
                ),
                ("trainee", models.BooleanField(default=False, verbose_name="研修中")),
            ],
            options={
                "verbose_name": "スキル区分",
                "verbose_name_plural": "スキル区分",
                "ordering": ["priority", "symbol"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="社員番号"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="氏名")),
                (
                    "public_holiday_count",
                    models.PositiveSmallIntegerField(
                        default=8, verbose_name="月公休数"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="その他・制約メモ")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "スタッフ",
                "verbose_name_plural": "スタッフ",
                "ordering": ["employee_number"],
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="業務名"),
                ),
                (
                    "required_staff_per_day",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="必要人数"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=7, verbose_name="色"),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="表示順"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "業務",
                "verbose_name_plural": "業務",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShiftPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(verbose_name="対象月")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "下書き"), ("published", "確定")],
                        default="draft",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "ordering": ["-month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("month",), name="unique_shift_period_month_v2"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShiftWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(blank=True, null=True, verbose_name="日付")),
                ("message", models.CharField(max_length=255, verbose_name="警告")),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to="shift_core.shiftperiod",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shift_core.staff",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shift_core.worktype",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "day",
                    "staff__employee_number",
                    "work_type__display_order",
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shift_core.skilllevel",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="shift_core.staff",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="shift_core.worktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフスキル",
                "verbose_name_plural": "スタッフスキル",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "work_type"), name="unique_staff_work_skill_v2"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="日付")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("work", "勤務"),
                            ("public_holiday", "公休"),
                            ("paid_leave", "有休"),
                            ("standby", "余剰"),
                        ],
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "自動"), ("manual", "手動")],
                        default="auto",
                        max_length=10,
                        verbose_name="作成元",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="shift_core.shiftperiod",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="shift_core.staff",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shift_core.worktype",
                    ),
                ),
            ],
            options={
                "ordering": ["staff__employee_number", "day"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period", "staff", "day"),
                        name="unique_shift_assignment_v2",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PreviousShiftRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="日付")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("work", "勤務"),
                            ("public_holiday", "公休"),
                            ("paid_leave", "有休"),
                            ("standby", "余剰"),
                            ("blank", "空欄"),
                        ],
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                (
                    "raw_value",
                    models.CharField(blank=True, max_length=100, verbose_name="取込値"),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_records",
                        to="shift_core.staff",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shift_core.worktype",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "staff__employee_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "day"), name="unique_previous_shift_record_v2"
                    )
                ],
            },
        ),
    ]
