# Generated by Django 5.2.15 on 2026-07-02 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="日付")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("public_holiday", "公休希望"),
                            ("paid_leave", "有休希望"),
                            ("unavailable", "勤務不可"),
                        ],
                        max_length=20,
                        verbose_name="希望",
                    ),
                ),
                (
                    "raw_value",
                    models.CharField(blank=True, max_length=100, verbose_name="取込値"),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_requests",
                        to="shift_core.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "staff__employee_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "day"), name="unique_shift_request_v2"
                    )
                ],
            },
        ),
    ]
