# Generated by Django 5.2.15 on 2026-06-22 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualconstraint',
            name='numeric_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='数値設定'),
        ),
        migrations.AddField(
            model_name='individualconstraint',
            name='related_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_constraints', to='shifts.staff', verbose_name='相手スタッフ'),
        ),
        migrations.AddField(
            model_name='individualconstraint',
            name='work_type_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraint_work_a', to='shifts.worktype', verbose_name='対象業務A'),
        ),
        migrations.AddField(
            model_name='individualconstraint',
            name='work_type_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraint_work_b', to='shifts.worktype', verbose_name='対象業務B'),
        ),
        migrations.CreateModel(
            name='ConstraintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='条件種別名')),
                ('operator', models.CharField(choices=[('max_consecutive', '最大連続勤務日数'), ('work_alternation', '指定した2業務を交互に配置'), ('incompatible_same_work', '指定スタッフ同士を同一業務へ同時配置しない'), ('avoid_same_work', '同一業務の連続を回避'), ('custom', '判定なし（備考・将来拡張用）')], max_length=40, verbose_name='判定方式')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('default_is_hard', models.BooleanField(default=True, verbose_name='初期値をHard Constraintにする')),
                ('active', models.BooleanField(default=True, verbose_name='有効')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraint_types', to='shifts.company')),
            ],
            options={
                'verbose_name': '条件種別',
                'verbose_name_plural': '条件種別',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='individualconstraint',
            name='rule_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constraints', to='shifts.constrainttype', verbose_name='条件種別'),
        ),
        migrations.AddConstraint(
            model_name='constrainttype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_constraint_type'),
        ),
    ]
