# Generated by Django 5.2.15 on 2026-06-24 05:39

import django.core.validators
from django.db import migrations, models


def migrate_hard_soft_to_strength(apps, schema_editor):
    ConstraintType = apps.get_model("shifts", "ConstraintType")
    IndividualConstraint = apps.get_model("shifts", "IndividualConstraint")

    for item in ConstraintType.objects.all():
        item.default_strength = 10 if item.default_is_hard else 5
        item.save(update_fields=["default_strength"])

    for item in IndividualConstraint.objects.all():
        item.strength = 10 if item.is_hard else 5
        item.save(update_fields=["strength"])


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0003_individualconstraint_text_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constrainttype",
            name="default_strength",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="10は絶対守る、1〜9は数字が大きいほど強く優先します。",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="初期強度",
            ),
        ),
        migrations.AddField(
            model_name="individualconstraint",
            name="strength",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="10は絶対守る、1〜9は数字が大きいほど強く優先します。",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="強度",
            ),
        ),
        migrations.RunPython(
            migrate_hard_soft_to_strength, reverse_code=migrations.RunPython.noop
        ),
    ]
