# Generated by Django 5.2.15 on 2026-06-24 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0004_constrainttype_default_strength_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worktype",
            name="required_staff_per_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="最低必要人数",
            ),
        ),
    ]
