# Generated by Django 5.2.15 on 2026-06-25 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0006_shiftleaverequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityday",
            name="paid_leave",
            field=models.BooleanField(default=False, verbose_name="有給希望"),
        ),
        migrations.AddField(
            model_name="staff",
            name="desired_off_limit",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="公休希望と有給希望を合わせて申請できる上限日数です。",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="希望上限日数",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="monthly_public_holidays",
            field=models.PositiveSmallIntegerField(
                default=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="月公休数",
            ),
        ),
        migrations.AlterField(
            model_name="availabilityday",
            name="preferred_off",
            field=models.BooleanField(default=False, verbose_name="公休希望"),
        ),
    ]
