# Generated by Django 5.2.15 on 2026-06-25 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0007_availabilityday_paid_leave_staff_desired_off_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worktype",
            name="required_staff_per_day",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="必要人数",
            ),
        ),
    ]
