# Generated by Django 5.2.15 on 2026-06-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0005_alter_worktype_required_staff_per_day"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="休み申請日")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="理由"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未対応"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                (
                    "admin_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="管理者メモ"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申請日時"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="対応日時"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_requests",
                        to="shifts.shiftassignment",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="shifts.shiftperiod",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="対応者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_leave_requests",
                        to="shifts.staff",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_leave_requests",
                        to="shifts.worktype",
                        verbose_name="対象業務",
                    ),
                ),
            ],
            options={
                "verbose_name": "急な休み申請",
                "verbose_name_plural": "急な休み申請",
                "ordering": ["status", "day", "staff__employee_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period", "staff", "day"),
                        name="unique_shift_leave_request_day",
                    )
                ],
            },
        ),
    ]
