# Generated by Django 5.2.15 on 2026-06-25 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0008_alter_worktype_required_staff_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="default_desired_off_limit",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="新しく追加されるスタッフへ自動反映する、公休希望と有給希望の合計上限です。",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="公有給希望上限",
            ),
        ),
    ]
