# Generated by Django 5.2.15 on 2026-06-25 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0009_company_default_desired_off_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviousMonthShiftDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="日付")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("work", "勤務"),
                            ("public_holiday", "公休"),
                            ("paid_leave", "有給"),
                            ("blank", "未入力"),
                        ],
                        max_length=20,
                        verbose_name="区分",
                    ),
                ),
                (
                    "raw_value",
                    models.CharField(blank=True, max_length=100, verbose_name="取込値"),
                ),
                (
                    "imported_at",
                    models.DateTimeField(auto_now=True, verbose_name="取込日時"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_shift_days",
                        to="shifts.company",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_shift_days",
                        to="shifts.staff",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_shift_days",
                        to="shifts.worktype",
                        verbose_name="業務",
                    ),
                ),
            ],
            options={
                "verbose_name": "先月シフト実績",
                "verbose_name_plural": "先月シフト実績",
                "ordering": ["staff__employee_number", "day"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "staff", "day"),
                        name="unique_previous_shift_company_staff_day",
                    )
                ],
            },
        ),
    ]
